// Bucket Keeper - AI Daily Plan Modal
// Personalized daily plan generated by AI with time blocks and priority badges

import React from 'react';
import {
  View,
  Text,
  FlatList,
  ActivityIndicator,
  Pressable,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useQuery } from '@tanstack/react-query';
import { useThemeColors, Card, GradientButton, Badge } from '../src/components/UIKit';
import { Typography, Spacing, BorderRadius, Layout, Shadows } from '../src/constants/theme';
import { Palette } from '../src/constants/colors';
import { aiApi } from '../src/utils/api';
import type { DailyPlanItem, Priority } from '../src/types';

function parsePlanItems(planStrings: string[]): DailyPlanItem[] {
  return planStrings.map((str, index) => {
    // Try to extract time block pattern like "[9:00 AM]" or "[Morning]"
    const timeMatch = str.match(/\[([^\]]+)\]\s*/);
    const timeBlock = timeMatch ? timeMatch[1] : null;
    const cleanedStr = timeMatch ? str.replace(timeMatch[0], '').trim() : str;

    // Assign priority based on position in the plan
    const priorities: Priority[] = ['high', 'high', 'medium', 'medium', 'low'];
    const priority: Priority = priorities[Math.min(index, priorities.length - 1)];

    return {
      title: cleanedStr,
      timeBlock,
      priority,
      suggestion: cleanedStr,
    };
  });
}

function getPriorityColor(priority: Priority): string {
  switch (priority) {
    case 'urgent':
      return Palette.priorityUrgent;
    case 'high':
      return Palette.priorityHigh;
    case 'low':
      return Palette.priorityLow;
    default:
      return Palette.priorityNormal;
  }
}

function getPriorityLabel(priority: Priority): string {
  switch (priority) {
    case 'urgent':
      return 'URGENT';
    case 'high':
      return 'HIGH';
    case 'low':
      return 'LOW';
    default:
      return 'MEDIUM';
  }
}

export default function AIDailyPlanScreen() {
  const router = useRouter();
  const colors = useThemeColors();

  const { data: planData, isLoading, error } = useQuery({
    queryKey: ['daily-plan'],
    queryFn: async () => {
      const response = await aiApi.getDailyPlan();
      return parsePlanItems(response.data.plan);
    },
    staleTime: 300000,
  });

  const renderPlanCard = ({ item, index }: { item: DailyPlanItem; index: number }) => (
    <Card style={{ marginBottom: Spacing.md }}>
      <View style={Layout.rowBetween}>
        <View style={{ flex: 1, marginRight: Spacing.md }}>
          {/* Time block */}
          {item.timeBlock && (
            <View style={{ ...Layout.row, marginBottom: Spacing.sm }}>
              <Ionicons name="time-outline" size={14} color={colors.primary} style={{ marginRight: 4 }} />
              <Text style={{ ...Typography.caption, color: colors.primary, fontWeight: '600' }}>
                {item.timeBlock}
              </Text>
            </View>
          )}

          {/* Suggestion text */}
          <Text style={{ ...Typography.body, color: colors.text, lineHeight: 22 }}>
            {item.suggestion}
          </Text>
        </View>

        {/* Priority badge */}
        <Badge
          text={getPriorityLabel(item.priority)}
          color={getPriorityColor(item.priority) + '20'}
          textColor={getPriorityColor(item.priority)}
        />
      </View>

      {/* Order indicator */}
      <View
        style={{
          position: 'absolute',
          top: -8,
          left: -8,
        }}
      >
        <LinearGradient
          colors={[colors.gradientStart, colors.gradientEnd]}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={{
            width: 28,
            height: 28,
            borderRadius: 14,
            ...Layout.center,
          }}
        >
          <Text style={{ ...Typography.tiny, color: '#FFF', fontWeight: '700' }}>
            {index + 1}
          </Text>
        </LinearGradient>
      </View>
    </Card>
  );

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: colors.background }}>
      {/* Header */}
      <View
        style={{
          ...Layout.rowBetween,
          paddingHorizontal: Spacing.screenHorizontal,
          paddingTop: Spacing.md,
          paddingBottom: Spacing.md,
        }}
      >
        <View style={{ width: 40 }} />
        <Text style={{ ...Typography.h3, color: colors.text }}>Daily Plan</Text>
        <Pressable
          onPress={() => router.back()}
          style={{
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: Palette.white10,
            ...Layout.center,
          }}
        >
          <Ionicons name="close" size={22} color={colors.text} />
        </Pressable>
      </View>

      {/* Title Section */}
      <View style={{ paddingHorizontal: Spacing.screenHorizontal, marginBottom: Spacing.lg }}>
        <Text style={{ ...Typography.h1, color: colors.text }}>
          Your AI Daily Plan
        </Text>
        <Text
          style={{
            ...Typography.body,
            color: colors.textSecondary,
            marginTop: Spacing.sm,
          }}
        >
          Personalized insights based on your real tasks and patterns.
        </Text>
      </View>

      {/* Loading State */}
      {isLoading && (
        <View style={{ flex: 1, ...Layout.center }}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text
            style={{
              ...Typography.h3,
              color: colors.text,
              marginTop: Spacing.lg,
            }}
          >
            Analyzing your data...
          </Text>
          <Text
            style={{
              ...Typography.bodySmall,
              color: colors.textSecondary,
              marginTop: Spacing.sm,
            }}
          >
            Building your personalized plan
          </Text>
        </View>
      )}

      {/* Error State */}
      {error && !isLoading && (
        <View style={{ flex: 1, ...Layout.center, paddingHorizontal: Spacing.xl }}>
          <Ionicons name="cloud-offline-outline" size={48} color={colors.textMuted} />
          <Text
            style={{
              ...Typography.body,
              color: colors.textMuted,
              textAlign: 'center',
              marginTop: Spacing.md,
            }}
          >
            Could not generate your daily plan. Please check your connection and try again.
          </Text>
        </View>
      )}

      {/* Plan List */}
      {planData && !isLoading && (
        <FlatList
          data={planData}
          renderItem={renderPlanCard}
          keyExtractor={(_, index) => `plan-${index}`}
          contentContainerStyle={{
            paddingHorizontal: Spacing.screenHorizontal,
            paddingTop: Spacing.sm,
            paddingBottom: 120,
          }}
          showsVerticalScrollIndicator={false}
          ListEmptyComponent={
            <Card>
              <Text
                style={{
                  ...Typography.body,
                  color: colors.textMuted,
                  textAlign: 'center',
                  paddingVertical: Spacing.lg,
                }}
              >
                No plan available yet. Complete some tasks and check back!
              </Text>
            </Card>
          }
        />
      )}

      {/* Bottom Button */}
      {!isLoading && planData && planData.length > 0 && (
        <View
          style={{
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            paddingHorizontal: Spacing.screenHorizontal,
            paddingBottom: Spacing.xl,
            paddingTop: Spacing.md,
            backgroundColor: colors.background + 'F0',
          }}
        >
          <GradientButton
            title="Sounds good!"
            onPress={() => router.back()}
            icon="thumbs-up"
            size="lg"
          />
        </View>
      )}
    </SafeAreaView>
  );
}
